export const FETCH_WEATHER_DATA = 'FETCH_WEATHER_DATA';
export const FETCH_HISTORICAL_WEATHER_DATA = 'FETCH_HISTORICAL_WEATHER_DATA';
export const FETCH_GRAPH_FORECAST_DATA = 'FETCH_GRAPH_FORECAST_DATA';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';

